// <auto-generated />
using System;
using ByteStormBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ByteStormBackend.Migrations
{
    [DbContext(typeof(ByteStormContext))]
    partial class ByteStormContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("ByteStormBackend.Models.Equipo", b =>
                {
                    b.Property<int>("EquipoCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<int>("EstadoEquipo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MisionID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("EquipoCodigo");

                    b.HasIndex("MisionID");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("ByteStormBackend.Models.Mision", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OperativoID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Codigo");

                    b.HasIndex("OperativoID");

                    b.ToTable("Misiones");
                });

            modelBuilder.Entity("ByteStormBackend.Models.Operativo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MisionAsignada")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Operativos");
                });

            modelBuilder.Entity("ByteStormBackend.Models.Equipo", b =>
                {
                    b.HasOne("ByteStormBackend.Models.Mision", "Mision")
                        .WithMany("Equipos")
                        .HasForeignKey("MisionID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Mision");
                });

            modelBuilder.Entity("ByteStormBackend.Models.Mision", b =>
                {
                    b.HasOne("ByteStormBackend.Models.Operativo", "Operativo")
                        .WithMany("Misiones")
                        .HasForeignKey("OperativoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operativo");
                });

            modelBuilder.Entity("ByteStormBackend.Models.Mision", b =>
                {
                    b.Navigation("Equipos");
                });

            modelBuilder.Entity("ByteStormBackend.Models.Operativo", b =>
                {
                    b.Navigation("Misiones");
                });
#pragma warning restore 612, 618
        }
    }
}
